package cg.usermanagement.model;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;

import cg.model.api.IEntity;


/*
 * one permission has one feature and one operation.
 * the name of the permission is <feature>_<operation>
 * the permission is not necessary to keep into the database as it can be generated by feature and operation
 */
public class Permission implements IEntity
{
  @SequenceGenerator( name = "TPERMISSION_SEQ" , sequenceName = "TPERMISSION_SEQ")
  @Id
  @GeneratedValue( strategy = javax.persistence.GenerationType.AUTO , generator = "TPERMISSION_SEQ")
  @Column( name = "ID" )
  private Long  id;

  @OneToOne(optional=false)
  @JoinColumn( name="FEATURE_ID", unique=true, nullable=false, updatable=false )
  private Feature feature;

  @OneToOne(optional=false)
  @JoinColumn( name="OPERATION_ID", unique=true, nullable=false, updatable=false )
  private Operation operation;

  @Override
  public Long getId()
  {
    return id;
  }
  @Override
  public void setId( Long id )
  {
    this.id = id;
  }

  public Feature getFeature()
  {
    return feature;
  }
  public void setFeature( Feature feature )
  {
    this.feature = feature;
  }

  public Operation getOperation()
  {
    return operation;
  }
  public void setOperation( Operation operation )
  {
    this.operation = operation;
  }

  
  public String getName()
  {
    return feature.getName() + "_" + operation.getName();
  }

}
