package cg.usermanagement.model;

import cg.model.api.IEntity;



/*
 * one permission has one feature and one operation.
 * the name of the permission is <feature>_<operation>
 * the permission is not necessary to keep into the database as it can be generated by feature and operation
 */
public class Permission implements IEntity
{
  private Feature feature;

  private Operation operation;

  public Permission( Feature feature, Operation operation )
  {
    setFeature( feature );
    setOperation( operation );
  }
  
  public Feature getFeature()
  {
    return feature;
  }
  public void setFeature( Feature feature )
  {
    this.feature = feature;
  }

  public Operation getOperation()
  {
    return operation;
  }
  public void setOperation( Operation operation )
  {
    this.operation = operation;
  }

  
  public String getName()
  {
    return feature.getName() + "_" + operation.getName();
  }
  

  // generate permission id according to feature/operation id
  @Override
  public Long getId()
  {
    return feature.getId() << 8 + operation.getId();
  }
  @Override
  public void setId( Long id )
  {
    // this method should not be called
    throw new RuntimeException( "Permission.setId() should not be called" );
    
  }

}
